name: golangci-lint
on:
  push:
    branches:
      - main
    paths:
      - "scai-gen/**"
  # Want to trigger these tests whenever the Go CLI or
  # APIs are modified
  pull_request:
    paths:
      - "scai-gen/**"
permissions:
  contents: read
jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c
        with:
          go-version: '1.22.x'
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10
      - name: golangci-lint
        uses: golangci/golangci-lint-action@82606bf257cbaff209d206a39f5134f0cfbfd2ee
        with:
          version: v1.60.3
